### ISSUE TITLE
Clone freedawoondental.my website

### ISSUE THREAD

**Issue by paragasu** [phisoft/freedawoondental-web#1]
Copy existing website

**Comment by shaifulazh** [comment]
wget --recursive --page-requisites --adjust-extension --span-hosts --convert-links --restrict-file-names=windows --user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" --domains freedawoondental.my --no-parent https://www.freedawoondental.my/
